# -*- coding: utf-8 -*-
"""Taller24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VobkCqRFN4v9CBoRnMxqIAaodntSAUcl
"""

def lagrange_interpolation(x_points, y_points):
    def L(k, x):
        result = 1.0
        for i in range(len(x_points)):
            if i != k:
                result *= (x - x_points[i]) / (x_points[k] - x_points[i])
        return result

    def P(x):
        result = 0.0
        for k in range(len(y_points)):
            result += y_points[k] * L(k, x)
        return result

    return P

# Puntos dados
x_points = [1, 2, 3, 4, 5]
y_points = [2, 1.8, -2, -4.6, 3.6]

# Crear el polinomio de interpolación de Lagrange
P = lagrange_interpolation(x_points, y_points)

# Ejemplo de uso: evaluar el polinomio en x=2.5
x_eval = 2.5
y_eval = P(x_eval)

print(f"El valor del polinomio en x={x_eval} es {y_eval}")