# -*- coding: utf-8 -*-
"""Taller21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n52BlN7ep4ZctOn_3MZRBey3srWBHS74
"""

import numpy as np
from scipy.stats import linregress


x = np.array([1, 3, 5, 7, 9, 11, 13])
y = np.array([7.4, 1.8, -1, -1.8, -1.2, 2.2, 7.2])


coefficients = np.polyfit(x, y, 2)
p = np.poly1d(coefficients)


slope, intercept, r_value, p_value, std_err = linregress(x, y)


print("Polinomio ajustado:")
print(p)


print("Coeficiente de correlación (r):", r_value)