# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0ia1uqgOXO8-hhDQTVwGs1asOXdrC22
"""

import numpy as np

# Datos
x1 = np.array([1, 1, 2, 3, 1, 2, 3, 3])
x2 = np.array([0, 1, 1, 2, 2, 3, 3, 1])
y = np.array([0.6, 2, 0.1, 0.3, 2.2, 2.3, 0.8, -1])

# Ajuste de la función lineal
X = np.column_stack((np.ones_like(x1), x1, x2))
coefficients, _, _, _ = np.linalg.lstsq(X, y, rcond=None)

# Coeficiente de correlación (r)
predicted_y = np.dot(X, coefficients)
correlation_matrix = np.corrcoef(y, predicted_y)
correlation_coefficient = correlation_matrix[0, 1]

print("Coeficientes de la función lineal:")
print("Intercepto:", coefficients[0])
print("Coeficiente para x1:", coefficients[1])
print("Coeficiente para x2:", coefficients[2])
print("Coeficiente de correlación (r):", correlation_coefficient)